swing_joint_left:
    joint_name: swing_joint_left

    hall_sensor:
        # spi parameters for hall sensor
        device: /dev/spidev1.0
        mode: 0x01 # SPI_CPHA
        bits: 16 # 16 bits per word
        speed: 500000 # 500kHz frequency
        delay: 0 # delay between transfers

    motor:
        can_name: can2
        can_id: 0x2
        
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 10
           
    position_controller:
        type: effort_controllers/JointPositionController
        joint: swing_joint_left
        pid: {p: 3.0, i: 2.5, d: 0.6, i_clamp_min: -10.0, i_clamp_max: 10.0, antiwindup: true}

swing_joint_right:
    joint_name: swing_joint_right

    hall_sensor:
        # spi parameters for hall sensor
        device: /dev/spidev1.0
        mode: 0x01 # SPI_CPHA
        bits: 16 # 16 bits per word
        speed: 500000 # 500kHz frequency
        delay: 0 # delay between transfers

    motor:
        can_name: can1
        can_id: 0x1
        
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 10
           
    position_controller:
        type: effort_controllers/JointPositionController
        joint: swing_joint_right
        pid: {p: 3.0, i: 2.5, d: 0.6, i_clamp_min: -10.0, i_clamp_max: 10.0, antiwindup: true}
        
extend_joint:
    joint_name: extend_joint

    rotary_encoder:
        #spi parameters for the arduino rotary encoder
        device: /dev/spidev1.0
        mode: 0 # standard spi mode
        bits: 8 # 8 bits per word
        speed: 200000 # 200kHz frequency
        delay: 0 # delay between transfers

    motor:
        can_name: can3
        can_id: 0x3
        
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 10
           
    position_controller:
        type: effort_controllers/JointPositionController
        joint: extend_joint
        pid: {p: 3.0, i: 2.5, d: 0.6, i_clamp_min: -10.0, i_clamp_max: 10.0, antiwindup: true}

