swing/left/joint:
    joint_name: swing/left/joint

    hall_sensor:
        # spi parameters for hall sensor
        spi_cs_id: 1 # chip select address (over multiplexer)
        spi_device: /dev/spidev1.0
        spi_mode: 0x01 # SPI_CPHA
        spi_bits: 16 # 16 bits per word
        spi_speed: 500000 # 500kHz frequency
        spi_delay: 0 # usec, delay after last bit transfer, before device deselect
        zero_point: 2.857

    motor:
        can_name: can1
        can_id: 0xd1
        
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100
           
    position_controller:
        type: effort_controllers/JointPositionController
        joint: swing/left/joint
        pid: {p: 100.0, i: 0.6, d: 0.4, i_clamp_min: -1.0, i_clamp_max: 1.0, antiwindup: true}


    effort_controller:
        type: effort_controllers/JointEffortController
        joint: swing/left/joint


    joint_limits:
        swing/left/joint:
              has_position_limits: true
              min_position: -1.0
              max_position: 1.0
              has_velocity_limits: true
              max_velocity: 6500
              has_acceleration_limits: false
              max_acceleration: 0.0
              has_jerk_limits: false
              max_jerk: 0
              has_effort_limits: true
              max_effort: 10




swing/right/joint:
    joint_name: swing/right/joint

    hall_sensor:
        # spi parameters for hall sensor
        spi_cs_id: 2 # chip select address (over multiplexer)
        spi_device: /dev/spidev1.0
        spi_mode: 0x01 # SPI_CPHA
        spi_bits: 16 # 16 bits per word
        spi_speed: 500000 # 500kHz frequency
        spi_delay: 0 # usec, delay after last bit transfer, before device deselect
        zero_point: 0.0

    motor:
        can_name: can1
        can_id: 0xd3
        
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 10
           
    position_controller:
        type: effort_controllers/JointPositionController
        joint: swing/right/joint
        pid: {p: 100, i: 0.6, d: 0.4, i_clamp_min: -1.0, i_clamp_max: 1.0, antiwindup: true}

    joint_limits:
            swing/right/joint:
              has_position_limits: true
              min_position: -1.2
              max_position: 1.2
              has_velocity_limits: true
              max_velocity: 6500
              has_acceleration_limits: false
              max_acceleration: 0.0
              has_jerk_limits: false
              max_jerk: 0
              has_effort_limits: true
              max_effort: 1
        
extend/joint:
    joint_name: extend/joint

    rotary_encoder:
        #spi parameters for the arduino rotary encoder
        spi_cs_id: 3 # chip select address (over multiplexer)
        spi_device: /dev/spidev1.0
        spi_mode: 0 # standard spi mode
        spi_bits: 8 # 8 bits per word
        spi_speed: 200000 # 200kHz frequency
        spi_delay: 0 # usec, delay after last bit transfer, before device deselect

    motor:
        can_name: can1
        can_id: 0xd2
        
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 10
           
    position_controller:
        type: effort_controllers/JointPositionController
        joint: extend/joint
        pid: {p: 3.0, i: 2.5, d: 0.6, i_clamp_min: -10.0, i_clamp_max: 10.0, antiwindup: true}


    joint_limits:
            extend/joint:
              has_position_limits: true
              min_position: -3.1416/2
              max_position: 3.1416/2
              has_velocity_limits: true
              max_velocity: 0.5
              has_acceleration_limits: false
              max_acceleration: 0.0
              has_jerk_limits: false
              max_jerk: 0
              has_effort_limits: true
              max_effort: 1

